import { Permission, UserRole } from '../types/auth';

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.SUPER_ADMIN]: Object.values(Permission),

  [UserRole.ADMIN]: [
    Permission.MANAGE_USERS,
    Permission.VIEW_USERS,
    Permission.MANAGE_ORDERS,
    Permission.VIEW_ORDERS,
    Permission.UPDATE_ORDER_STATUS,
    Permission.MANAGE_INVENTORY,
    Permission.VIEW_INVENTORY,
    Permission.MANAGE_FINANCES,
    Permission.VIEW_FINANCES,
    Permission.MANAGE_SETTINGS,
    Permission.VIEW_SETTINGS,
    Permission.VIEW_REPORTS,
    Permission.EXPORT_REPORTS,
    Permission.MANAGE_STAFF,
    Permission.VIEW_STAFF,
    Permission.MANAGE_DELIVERY,
    Permission.VIEW_DELIVERY,
    Permission.MANAGE_PAYMENTS,
    Permission.VIEW_PAYMENTS,
    Permission.MANAGE_PRODUCTS,
    Permission.VIEW_PRODUCTS,
    Permission.MANAGE_REVIEWS,
    Permission.MODERATE_REVIEWS,
    Permission.MANAGE_MARKETPLACE,
    Permission.VIEW_AUDIT_LOGS,
    Permission.MANAGE_MODULES,
  ],

  [UserRole.MANAGER]: [
    Permission.VIEW_USERS,
    Permission.MANAGE_ORDERS,
    Permission.VIEW_ORDERS,
    Permission.UPDATE_ORDER_STATUS,
    Permission.MANAGE_INVENTORY,
    Permission.VIEW_INVENTORY,
    Permission.MANAGE_FINANCES,
    Permission.VIEW_FINANCES,
    Permission.VIEW_REPORTS,
    Permission.EXPORT_REPORTS,
    Permission.MANAGE_STAFF,
    Permission.VIEW_STAFF,
    Permission.MANAGE_DELIVERY,
    Permission.VIEW_DELIVERY,
    Permission.MANAGE_PAYMENTS,
    Permission.VIEW_PAYMENTS,
    Permission.MANAGE_PRODUCTS,
    Permission.VIEW_PRODUCTS,
    Permission.MANAGE_REVIEWS,
  ],

  [UserRole.TAILOR_SHOP]: [
    Permission.VIEW_USERS,
    Permission.MANAGE_ORDERS,
    Permission.VIEW_ORDERS,
    Permission.UPDATE_ORDER_STATUS,
    Permission.MANAGE_INVENTORY,
    Permission.VIEW_INVENTORY,
    Permission.VIEW_FINANCES,
    Permission.VIEW_REPORTS,
    Permission.MANAGE_STAFF,
    Permission.VIEW_STAFF,
    Permission.MANAGE_DELIVERY,
    Permission.VIEW_DELIVERY,
    Permission.MANAGE_PAYMENTS,
    Permission.VIEW_PAYMENTS,
    Permission.MANAGE_PRODUCTS,
    Permission.VIEW_PRODUCTS,
    Permission.MANAGE_REVIEWS,
  ],

  [UserRole.STAFF]: [
    Permission.VIEW_ORDERS,
    Permission.UPDATE_ORDER_STATUS,
    Permission.VIEW_INVENTORY,
    Permission.VIEW_DELIVERY,
    Permission.VIEW_PRODUCTS,
    Permission.VIEW_STAFF,
  ],

  [UserRole.MERCHANT]: [
    Permission.VIEW_ORDERS,
    Permission.MANAGE_INVENTORY,
    Permission.VIEW_INVENTORY,
    Permission.VIEW_FINANCES,
    Permission.MANAGE_PRODUCTS,
    Permission.VIEW_PRODUCTS,
    Permission.MANAGE_MARKETPLACE,
    Permission.VIEW_REPORTS,
  ],

  [UserRole.TAILOR]: [
    Permission.VIEW_ORDERS,
    Permission.UPDATE_ORDER_STATUS,
    Permission.VIEW_INVENTORY,
    Permission.VIEW_PRODUCTS,
    Permission.VIEW_STAFF,
  ],

  [UserRole.CUSTOMER]: [
    Permission.VIEW_ORDERS,
    Permission.VIEW_PRODUCTS,
    Permission.MANAGE_REVIEWS,
  ],
};
